### ISSUE TITLE
Api security

### ISSUE THREAD

**Issue by NiekvDommelen** [NiekvDommelen/whisper#20]
# API security

## todo
 - [x]  make the api use https
 - [x]  delete previous token when a new token is created 

# security

We can not have people acces our API outside the app. So we need to research a way to keep the API from being accessible outside of the app. Some ways we can do this:

- single topen
- rotating token
- temporary acces token

## single token
This is a simple solution where we require every API request to contain a key that is checked on the server. If the key is correct we respond appropriately and if not we return a error. 

### vulnerability
Because the key stays the same if someone somehow gets this key they can freely use the API and the key will need to be changed and every app needs to be updated.

## rotating token
Every user has a different token, When they send a API request a new token is created and is included in the servers response. The old token is not active anymore and the user should use the new token.

### vulnerability
If the key is captured once it can be used continuously as a new token is returned to the sender. Also the original user wont be able to use there app as they have the old token and cant get a new one.

**Comment by NiekvDommelen** [comment]
## todo

 - [ ]  hash passwords on client side
 - [ ]  generate hashed api tokens on login
 - [ ]  delete previous token when a new token is created
